export const APP_ENUMS = {
  orderStatuses: [
    { value: 'PENDING', label: 'Pending' },
    { value: 'ACCEPTED', label: 'Accepted' },
    { value: 'IN_PROGRESS', label: 'In Progress' },
    { value: 'VERIFICATION', label: 'Verification' },
    { value: 'COMPLETED', label: 'Completed' },
    { value: 'CANCELLED', label: 'Cancelled' },
  ],
  assetTypes: [
    { value: 'BILLBOARD', label: 'Billboard' },
    { value: 'TRANSIT', label: 'Transit' },
    { value: 'INDOOR', label: 'Indoor' },
    { value: 'DIGITAL', label: 'Digital' },
  ],
  publisherTypes: [
    { value: 'INDIVIDUAL', label: 'Individual' },
    { value: 'BUSINESS', label: 'Business / Agency' },
    { value: 'NGO', label: 'NGO / Trust' },
    { value: 'POLITICAL', label: 'Political Party' },
  ],
  kycStatuses: [
    { value: 'PENDING', label: 'Pending' },
    { value: 'VERIFIED', label: 'Verified' },
    { value: 'REJECTED', label: 'Rejected' },
  ],
  listingCategories: [
    { value: 'INDOOR', label: 'Indoor', description: 'Mall, cinema, office, hotel' },
    { value: 'OUTDOOR', label: 'Outdoor', description: 'Billboards, kiosks, walls' },
    { value: 'TRANSIT', label: 'Transit', description: 'Bus, metro, airport, cab' },
    { value: 'MEDIA', label: 'Media', description: 'DOOH, interactive, vehicle' },
  ],
  listingStatuses: [
    { value: 'DRAFT', label: 'Draft' },
    { value: 'PENDING_REVIEW', label: 'Pending Review' },
    { value: 'ACTIVE', label: 'Active' },
    { value: 'REJECTED', label: 'Rejected' },
    { value: 'INACTIVE', label: 'Inactive' },
  ],
  notificationTypes: [
    { value: 'BOOKING', label: 'Booking' },
    { value: 'PAYOUT', label: 'Payout' },
    { value: 'KYC', label: 'KYC' },
    { value: 'MESSAGE', label: 'Message' },
    { value: 'SYSTEM', label: 'System' },
  ],
  milestoneTypes: [
    { value: 'ONBOARDING', label: 'Onboarding' },
    { value: 'REVENUE', label: 'Revenue' },
    { value: 'ACTIVITY', label: 'Activity' },
    { value: 'QUALITY', label: 'Quality' },
  ],
  ticketCategories: [
    { value: 'payout', label: 'Payout Issue' },
    { value: 'kyc', label: 'KYC / Verification' },
    { value: 'order', label: 'Order Problem' },
    { value: 'listing', label: 'Listing Issue' },
    { value: 'other', label: 'Other' },
  ],
  languages: [
    { value: 'en', label: 'English' },
    { value: 'hi', label: 'Hindi' },
    { value: 'kn', label: 'Kannada' },
    { value: 'ta', label: 'Tamil' },
    { value: 'te', label: 'Telugu' },
    { value: 'mr', label: 'Marathi' },
  ],
  agentTiers: [
    { value: 'BRONZE', label: 'Bronze Agent' },
    { value: 'SILVER', label: 'Silver Agent' },
    { value: 'GOLD', label: 'Gold Agent' },
    { value: 'PLATINUM', label: 'Platinum Agent' },
  ],
};
