-- Lot X: one catalogue city key on every row that carries a free-text city, backfilled by name and alias.
ALTER TABLE "Publisher" ADD COLUMN "cityId" TEXT;
CREATE INDEX "Publisher_cityId_idx" ON "Publisher"("cityId");
ALTER TABLE "Publisher" ADD CONSTRAINT "Publisher_cityId_fkey" FOREIGN KEY ("cityId") REFERENCES "City"("id") ON DELETE SET NULL ON UPDATE CASCADE;
UPDATE "Publisher" t SET "cityId" = c."id" FROM "City" c WHERE t."cityId" IS NULL AND t."city" IS NOT NULL AND (lower(trim(t."city")) = lower(c."name") OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = c."slug" OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = ANY(c."aliases"));
ALTER TABLE "Advertiser" ADD COLUMN "cityId" TEXT;
CREATE INDEX "Advertiser_cityId_idx" ON "Advertiser"("cityId");
ALTER TABLE "Advertiser" ADD CONSTRAINT "Advertiser_cityId_fkey" FOREIGN KEY ("cityId") REFERENCES "City"("id") ON DELETE SET NULL ON UPDATE CASCADE;
UPDATE "Advertiser" t SET "cityId" = c."id" FROM "City" c WHERE t."cityId" IS NULL AND t."city" IS NOT NULL AND (lower(trim(t."city")) = lower(c."name") OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = c."slug" OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = ANY(c."aliases"));
ALTER TABLE "AgentProfile" ADD COLUMN "cityId" TEXT;
CREATE INDEX "AgentProfile_cityId_idx" ON "AgentProfile"("cityId");
ALTER TABLE "AgentProfile" ADD CONSTRAINT "AgentProfile_cityId_fkey" FOREIGN KEY ("cityId") REFERENCES "City"("id") ON DELETE SET NULL ON UPDATE CASCADE;
UPDATE "AgentProfile" t SET "cityId" = c."id" FROM "City" c WHERE t."cityId" IS NULL AND t."city" IS NOT NULL AND (lower(trim(t."city")) = lower(c."name") OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = c."slug" OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = ANY(c."aliases"));
ALTER TABLE "PrintPartner" ADD COLUMN "cityId" TEXT;
CREATE INDEX "PrintPartner_cityId_idx" ON "PrintPartner"("cityId");
ALTER TABLE "PrintPartner" ADD CONSTRAINT "PrintPartner_cityId_fkey" FOREIGN KEY ("cityId") REFERENCES "City"("id") ON DELETE SET NULL ON UPDATE CASCADE;
UPDATE "PrintPartner" t SET "cityId" = c."id" FROM "City" c WHERE t."cityId" IS NULL AND t."city" IS NOT NULL AND (lower(trim(t."city")) = lower(c."name") OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = c."slug" OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = ANY(c."aliases"));
ALTER TABLE "Listing" ADD COLUMN "cityId" TEXT;
CREATE INDEX "Listing_cityId_idx" ON "Listing"("cityId");
ALTER TABLE "Listing" ADD CONSTRAINT "Listing_cityId_fkey" FOREIGN KEY ("cityId") REFERENCES "City"("id") ON DELETE SET NULL ON UPDATE CASCADE;
UPDATE "Listing" t SET "cityId" = c."id" FROM "City" c WHERE t."cityId" IS NULL AND t."city" IS NOT NULL AND (lower(trim(t."city")) = lower(c."name") OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = c."slug" OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = ANY(c."aliases"));
ALTER TABLE "Lead" ADD COLUMN "cityId" TEXT;
CREATE INDEX "Lead_cityId_idx" ON "Lead"("cityId");
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_cityId_fkey" FOREIGN KEY ("cityId") REFERENCES "City"("id") ON DELETE SET NULL ON UPDATE CASCADE;
UPDATE "Lead" t SET "cityId" = c."id" FROM "City" c WHERE t."cityId" IS NULL AND t."city" IS NOT NULL AND (lower(trim(t."city")) = lower(c."name") OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = c."slug" OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = ANY(c."aliases"));
ALTER TABLE "FieldVisit" ADD COLUMN "cityId" TEXT;
CREATE INDEX "FieldVisit_cityId_idx" ON "FieldVisit"("cityId");
ALTER TABLE "FieldVisit" ADD CONSTRAINT "FieldVisit_cityId_fkey" FOREIGN KEY ("cityId") REFERENCES "City"("id") ON DELETE SET NULL ON UPDATE CASCADE;
UPDATE "FieldVisit" t SET "cityId" = c."id" FROM "City" c WHERE t."cityId" IS NULL AND t."city" IS NOT NULL AND (lower(trim(t."city")) = lower(c."name") OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = c."slug" OR lower(regexp_replace(trim(t."city"), '[^a-zA-Z0-9]+', '-', 'g')) = ANY(c."aliases"));
ALTER TABLE "Campaign" ADD COLUMN "targetMarketCityId" TEXT;
CREATE INDEX "Campaign_targetMarketCityId_idx" ON "Campaign"("targetMarketCityId");
ALTER TABLE "Campaign" ADD CONSTRAINT "Campaign_targetMarketCityId_fkey" FOREIGN KEY ("targetMarketCityId") REFERENCES "City"("id") ON DELETE SET NULL ON UPDATE CASCADE;
UPDATE "Campaign" t SET "targetMarketCityId" = c."id" FROM "City" c WHERE t."targetMarketCityId" IS NULL AND t."targetMarket" IS NOT NULL AND (lower(trim(t."targetMarket")) = lower(c."name") OR lower(regexp_replace(trim(t."targetMarket"), '[^a-zA-Z0-9]+', '-', 'g')) = c."slug" OR lower(regexp_replace(trim(t."targetMarket"), '[^a-zA-Z0-9]+', '-', 'g')) = ANY(c."aliases"));
