import { feature } from '../../shared/features';

/**
 * Features of `invoices` — Lot G (answer 144).
 *
 * The paper, never the money (Lot B, Q13/Q34).
 *
 * One key per user-facing capability. Route prefixes cover the module's
 * routes for tests/architecture/feature-registry.test.ts; the longest
 * declared prefix wins, so the root prefix is the safety net.
 */

feature('finance.invoices', {
  surfaces: ['APP_USER', 'CONSOLE'],
  owner: 'finance',
  kind: 'FEATURE',
  launch: 'on',
  description:
    'ADX\'s invoices to advertisers, publishers\' invoices to ADX, the legal entity behind them.',
  routes: [
    '/api/v1/finance/legal-entity',
    '/api/v1/finance/invoices',
    '/api/v1/finance/publisher-invoices',
    '/api/v1/advertisers/:id/invoices',
    '/api/v1/publishers/me/invoices',
  ],
});

feature('finance.statements', {
  surfaces: ['APP_USER', 'APP_AGENT', 'CONSOLE', 'BACKEND'],
  owner: 'finance',
  kind: 'FEATURE',
  launch: 'on',
  description:
    'The monthly payment advice per wallet, generated by the job and read back as PDF.',
  routes: ['/api/v1/finance/statements', '/api/v1/payouts/wallet/statements'],
  jobs: ['monthly-statements'],
});
